@startuml
title Book Show - Payment Failure

actor User
participant BookMyShow
participant BookingService
participant ShowSeat
participant PaymentService
participant Booking

User -> BookMyShow: bookShow(userId, showId, venueId, seatIds)
BookMyShow -> BookingService: bookShow(user, show, requestedSeats)

BookingService -> Booking: new Booking(id, show, requestedSeats, user)\n[status = PENDING]

loop for each ShowSeat in requestedSeats
    BookingService -> ShowSeat: isAvailable()
    ShowSeat --> BookingService: true
end

loop for each ShowSeat in requestedSeats
    BookingService -> ShowSeat: lock()
    BookingService -> Booking: updatePrice(showSeat.getPrice())
end

BookingService -> PaymentService: processPayment(booking.getPrice())
PaymentService --> BookingService: false

loop for each ShowSeat in requestedSeats
    BookingService -> ShowSeat: release()
end

BookingService -> Booking: updateStatus(FAILED)
BookingService --> BookMyShow: throws PaymentFailureException
BookMyShow --> User: booking failed

@enduml