@startuml
title Turn Sequence FloralWhite
    participant SnakeAndLadderMain
    participant SnakeAndLadderGame
    participant PlayerFactory
    participant Board
    participant TurnManager

    SnakeAndLadderMain->>SnakeAndLadderGame: new SnakeAndLadderGame(playerInfos)
    SnakeAndLadderGame->>Board: new Board()
    activate Board
    Board->>Board: generateJumps()
    deactivate Board

    loop for each PlayerInfo
        SnakeAndLadderGame->>PlayerFactory: createPlayer(indicator, name)
        PlayerFactory-->>SnakeAndLadderGame: Player
        SnakeAndLadderGame->>SnakeAndLadderGame: players.add(player)
        SnakeAndLadderGame->>Board: registerPlayer(player)
    end

    SnakeAndLadderGame->>TurnManager: new TurnManager(players)
    SnakeAndLadderMain->>SnakeAndLadderGame: start()
@enduml