@startuml
title Entrance Flow

participant Main
participant ParkingLot
participant VehicleFactory
participant SlotAssignment

Main -> ParkingLot: entry(vehicleType, plateNumber, ownerName)
ParkingLot -> VehicleFactory: createVehicle(vehicleType, plateNumber, ownerName)
VehicleFactory --> ParkingLot: Vehicle
ParkingLot -> SlotAssignment: assign(vehicle, slotsMap)
SlotAssignment --> ParkingLot: ParkingSlot
ParkingLot -> ParkingLot: createTicket(parkingSlot, vehicle)
ParkingLot --> Main: Ticket

@enduml