@startuml
title Pin Failure Flow  - Negative Path

participant Main
participant ATM
participant PinEntryState
participant Card

Main -> ATM: enterPin(pin)
ATM -> PinEntryState: enterPin(pin, this)
PinEntryState -> Card: getPin()
Card --> PinEntryState: cardPin
PinEntryState -> PinEntryState: isValid = (pin == cardPin)

alt isValid == true
    PinEntryState -> ATM: setState(new AmountEntryState)
else isValid == false
    PinEntryState -> ATM: setRetryAttempt(atm.getRetryAttempt() + 1)
    alt atm.getRetryAttempt() >= 3
        PinEntryState -> ATM: eject()
    else atm.getRetryAttempt() < 3
        PinEntryState --> ATM: void
    end
end

PinEntryState --> ATM: void
ATM --> Main: void

@enduml